### ISSUE TITLE
Message from cross platform not received in iOS

### ISSUE THREAD

**Issue by NadeemIqbal** [twilio/twilio-conversations-demo-ios-swift#1]
Message is sending and receiving on iOS to iOS devices. but not receiving any messages on iOS from any other platform like Android and Web(React).

**Comment by whoisarte** [comment]
Hi, I have this problem too. But, in conversationsList view, there are the number of messages received from other users in the conversation increase, but in the conversation view doesn't show that messages. It is just a problem to show the messages

**Comment by whoisarte** [comment]
Hi, I catched up what's the problem (partially) when I received messages from not iOS devices. Is in ConversationsDataConverter file. The "guard let" sentence that tries to catch uuid value always came nil from web and android devices (using other demo projects), when it tries to parse the following sentence: "message.attributes()?.toStringBasedDictionary()["uuid"] as? String".
Then, because it is empty, the flow enters to the "else" block in the guard let, and makes a nil return.

I solve it by making a new UUID with UUID() constructor, to generate a random identifier when it comes nil or when it fails to parse. I still think this is not the best solution but partially it works nice.

`
func convert(message: TCHMessage) -> MessageDataItem? {
        var uuid = ""
        if let uuidFromMessage = message.attributes()?.toStringBasedDictionary()["uuid"] as? String {
            uuid = uuidFromMessage
            print("UUID from iOS Device -> \(uuid)")
        } else {
            print("Not catched uuid (making random one...)")
        }
        guard let messageSid = message.sid else { return nil }
        return MessageDataItem(sid: messageSid,
                               uuid: uuid.isEmpty || uuid == "" ? UUID().uuidString : uuid,
                               index: message.index as! UInt,
                               direction: MessageDirection.outgoing,
                               author: message.author ?? "",
                               body: message.body ?? "",
                               dateCreated: message.dateCreatedAsDate?.timeIntervalSince1970 ?? 0,
                               sendStatus: MessageSendStatus.undefined,
                               conversationSid: "",
                               type: message.messageType,
                               mediaSid: message.mediaSid,
                               reactions: MessageReactionsModel.fromAttributes(jsonAttributes: message.attributes()),
                               mediaStatus: .none
                            )
    }
`

**Comment by whoisarte** [comment]
Hi, I catched up what's the problem (partially) when I received messages from not iOS devices. Is in ConversationsDataConverter file. The "guard let" sentence that tries to catch uuid value always came nil from web and android devices (using other demo projects), when it tries to parse the following sentence: "message.attributes()?.toStringBasedDictionary()["uuid"] as? String".
Then, because it is empty, the flow enters to the "else" block in the guard let, and makes a nil return.

I solve it by making a new UUID with UUID() constructor, to generate a random identifier when it comes nil or when it fails to parse. I still think this is not the best solution but partially it works nice.

```

func convert(message: TCHMessage) -> MessageDataItem? {
        var uuid = ""
        if let uuidFromMessage = message.attributes()?.toStringBasedDictionary()["uuid"] as? String {
            uuid = uuidFromMessage
            print("UUID from iOS Device -> \(uuid)")
        } else {
            print("Not catched uuid (making random one...)")
        }
        guard let messageSid = message.sid else { return nil }
        return MessageDataItem(sid: messageSid,
                               uuid: uuid.isEmpty || uuid == "" ? UUID().uuidString : uuid,
                               index: message.index as! UInt,
                               direction: MessageDirection.outgoing,
                               author: message.author ?? "",
                               body: message.body ?? "",
                               dateCreated: message.dateCreatedAsDate?.timeIntervalSince1970 ?? 0,
                               sendStatus: MessageSendStatus.undefined,
                               conversationSid: "",
                               type: message.messageType,
                               mediaSid: message.mediaSid,
                               reactions: MessageReactionsModel.fromAttributes(jsonAttributes: message.attributes()),
                               mediaStatus: .none
                            )
    }

```
